### ISSUE TITLE
Can't seem to get GOG Connect endpoints?

### ISSUE THREAD

**Issue by cardonator** [Yepoleb/pygogapi#1]
Hello, I used a portion of this code to write a script that checks GOG Connect to see if there are new products on there to import. However, the documentation wasn't clear that the User ID you are supposed to pass to those endpoints actually comes from the userData.json and not from the authorized response when getting an access_token.

Might be worth improving the documentation there.

**Comment by Yepoleb** [comment]
I think this is a gogapidocs issue, I created one there: https://github.com/Yepoleb/gogapidocs/issues/1

Sorry for the slow response time, my notification settings were wrong.
