### ISSUE TITLE
Unable to use api.search()

### ISSUE THREAD

**Issue by Stapper** [Yepoleb/pygogapi#2]
How is one supposed to use the search, websearch function?
I have tried several arguments. Every time I pass in an argument I get
`TypeError: search() takes 1 positional argument but 2 were given`

**Comment by Yepoleb** [comment]
It supports keyword arguments only, like this:

    api.search(mediaType="game", sort="bestselling")

**Comment by Stapper** [comment]
Thank you so much.

**Comment by Yepoleb** [comment]
No problem! Sorry for the bad documentation, I should really look into setting up a Doxygen or something similar.
